[package]
name = "comb"
version = "0.1.0"
authors = ["Skyler Calaman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
run_script = "0.7.0"
fs_extra = "1.2.0"
shellexpand = "1.0.0"
